version: '3.2'

services:
  lamp:
    build:
      context: ./lamp
    volumes:
      - ./app/:/var/www/html
      - ./lamp/rewrite.load:/etc/apache2/mods-enabled/rewrite.load
      - ./lamp/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5430:5432
    volumes:
      - ./pg/initial_pg/:/docker-entrypoint-initdb.d/
